### ISSUE TITLE
k8s_info doesn't show "Route" resources

### ISSUE THREAD

**Issue by nathanegillett** [ansible-collections/community.okd#21]
##### SUMMARY
When using k8s_info module to get select resources under a namespace, none of kind "Route" are returned.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
k8s_info

##### ANSIBLE VERSION

```paste below
$ ansible --version
ansible 2.9.13
  config file = None
  configured module search path = ['/home/ngillett/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ngillett/dev/python3/lib/python3.7/site-packages/ansible
  executable location = /home/ngillett/dev/python3/bin/ansible
  python version = 3.7.9 (default, Aug 20 2020, 14:07:20) [GCC 10.2.1 20200723 (Red Hat 10.2.1-1)]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

```
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	Fedora
Description:	Fedora release 32 (Thirty Two)
Release:	32
Codename:	ThirtyTwo
```

##### STEPS TO REPRODUCE

Create route resources in OpenShift, use k8s_info to fetch them.

```yaml
- name: Find existing resources
  k8s_info:
    api_key: "{{ exodus_gw_ocp_token }}"
    host: "{{ exodus_gw_ocp_host }}"
    namespace: "{{ exodus_gw_ocp_namespace }}"
    kind: "{{ item }}"
    ca_cert: "{{ exodus_gw_ca_cert }}"
  register: exodus_gw_resources
  with_items:
    - Pod
    - Service
    - ImageStream
    - DeploymentConfig
    - ReplicationController
    - NetworkPolicy
    - Route
```

##### EXPECTED RESULTS

Given that route resources exist under the namespace, they should be listed by the above.
```
$ oc get --namespace=exodus-gw-qa route
NAME                                             HOST/PORT                                   PATH      SERVICES    PORT      TERMINATION   WILDCARD
exodus-gw-qa.apps.ocp.prod.psi.redhat.com-host   exodus-gw-qa.apps.ocp.prod.psi.redhat.com             exodus-gw   http      edge          None
exodus-gw.qa.psi.redhat.com-cname                exodus-gw.qa.psi.redhat.com                           exodus-gw   http      edge          None
```

##### ACTUAL RESULTS

```paste below
ok: [exodus-gw-qa-project] => (item=Route) => {
    "ansible_loop_var": "item",
    "changed": false,
    "invocation": {
        "module_args": {
            "api_key": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "api_version": "v1",
            "ca_cert": "/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem",
            "client_cert": null,
            "client_key": null,
            "context": null,
            "field_selectors": [],
            "host": "https://api.ocp.prod.psi.redhat.com:6443",
            "kind": "Route",
            "kubeconfig": null,
            "label_selectors": [],
            "name": null,
            "namespace": "exodus-gw-qa",
            "password": null,
            "proxy": null,
            "username": null,
            "validate_certs": null
        }
    },
    "item": "Route",
    "resources": []
}
```
