### ISSUE TITLE
New Module: openshift_route

### ISSUE THREAD

**Issue by tima** [ansible-collections/community.okd#31]
##### SUMMARY

Create a module that emulates the logic of the`oc expose` command in an Ansible native-way.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

plugins/modules/openshift_route.py

##### ADDITIONAL INFORMATION

One could create the necessary route interfaces to something like a service using a series of lookups and templatized `k8s` resource declarations without this module. The idea is to make that easy and more efficient here by abstracting automation developers away from need to understand and handle it themselves. This also has the benefit of making Ansible plays be more concise and readable.

UPDATE: [It was noted](https://github.com/ansible-collections/community.okd/issues/31#issuecomment-689257177) that there is a `kubectl expose` command that `oc expose` builds upon. Further, [it was suggested that we refrain from overloading the term "expose"](https://github.com/ansible-collections/community.okd/issues/31#issuecomment-700922955) given their different implementations in Kubernetes and OpenShift and opt for turns that describe the object the modify. We will create this module first and look to create related module(s) in the kubernetes collection with only that native functionality.

**Comment by darthlukan** [comment]
Proposed interaction may look like:

```
tasks:
- name: Expose Service
  okd.expose:
     service: "{{ name }}"
     namespace: "{{ namespace }}"
     args:
       - hostname: "{{ hostname }}"
     kubeconfig: "{{ kubeconfig }}"
```
