### ISSUE TITLE
Create an openshift_process module that functionally corresponds to `oc process` subcommand

### ISSUE THREAD

**Issue by tima** [ansible-collections/community.okd#43]
##### SUMMARY

This feature is to supplement Template resources in OpenShift. (Template resource support is being handled through #22.) The `k8s` module can handle the standard CRUD operations for managing Template resources.  A supplementary module it needed to handle the parts of the OpenShift Templates implementation that cannot be expressed via the generic `k8s` interface.

Since these  additional operations correspond pretty much exactly to the `oc process` command, this module will be called `openshift_process`. This naming will also help differentiate Template resources from these imperative operations.
 
This module would basically accept either a template name, file, or definition, and the parameters that should be set, and will properly send that request to the API server. 

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

plugins/modules/openshift_process.py

##### ADDITIONAL INFORMATION

Here is an example of what a task would look like using this proposed module:

```yaml
community.okd.openshift_process:
  name: nginx-example
  namespace: openshift # only needed if using a template already on the server
  parameters:
    NAMESPACE: default
    NAME: test123
    GITHUB_WEBHOOK_SECRET: '{{ gh_secret }}'
```
