### ISSUE TITLE
Getting deprecation warning 'KubernetesRawModule is deprecated' with k8s module

### ISSUE THREAD

**Issue by geerlingguy** [ansible-collections/community.okd#56]
##### SUMMARY

When I use `community.okd.k8s` I get a warning message.

```
[WARNING]: class KubernetesRawModule is deprecated and will be removed in 2.0.0. Please use K8sAnsibleMixin instead.
```

##### ISSUE TYPE

- Bug Report

##### COMPONENT NAME

community.okd.k8s

##### ANSIBLE VERSION

2.10.3

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

macOS/Linux

##### STEPS TO REPRODUCE

```yaml
---
- hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - redhat.openshift.k8s:
        name: testing
        api_version: v1
        kind: Namespace
        state: present
```

##### EXPECTED RESULTS

Task should work, no errors or warnings.

##### ACTUAL RESULTS

```
 _____________________________ 
< TASK [redhat.openshift.k8s] >
 ----------------------------- 
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

[WARNING]: class KubernetesRawModule is deprecated and will be removed in 2.0.0. Please use K8sAnsibleMixin instead.
changed: [127.0.0.1]
```
